### ISSUE TITLE
todo list

### ISSUE THREAD

**Issue by derhuerst** [public-transport/generating-transit-maps#6]
In order to keep an overview over our scattered discussions.

- [ ] throw [`TransitmapSolver.jl`](https://github.com/dirkschumacher/TransitmapSolver.jl) into a Docker container
- [ ] publish 2nd paper implementation @juliuste
- [ ] have a look at [this other paper](https://modl.jhu.edu/wp-content/uploads/2016/02/2015OkeSiddiqui.pdf)
- [x] finish [`vbb-graph-computation-server`](https://github.com/derhuerst/vbb-graph-computation-server) @derhuerst – it's obsolete by now
- [ ] find a way to handle reasonably large graph (e.g. Europe-wide)
- [ ] [interactive modelling tool](https://github.com/public-transport/generating-transit-maps/blob/e8fd599/readme.md#outlook-interactive-modelling-tool) – see [transit-map-generator](https://github.com/derhuerst/transit-map-generator#transit-map-generator) for a first draft
- [ ] find a place to put generated graphs & rendered maps
- [ ] find a way to avoid intersecting lines
- [ ] add support for node labeling
- [ ] make [`vbb-map-routing`](https://github.com/derhuerst/vbb-map-routing) support the exported maps – @derhuerst

**Comment by derhuerst** [comment]
- [ ] https://modl.jhu.edu/wp-content/uploads/2016/02/2015OkeSiddiqui.pdf
- [ ] https://run.unl.pt/bitstream/10362/18403/1/TGEO0150.pdf
